name: Check Format
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - '**'

jobs:
  lint:
    name: Check code base format
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3

      - uses: DoozyX/clang-format-lint-action@v0.14
        with:
          source: '. src'
          extensions: 'h,cpp,ino'
          clangFormatVersion: 16
