name: Lint
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - '**'

jobs:
  lint:
    name: Check code base Format
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: Ballen7/clang-format-lint-action@clang-format-16
        with:
          source: '. src'
          extensions: 'h,cpp,ino'
          clangFormatVersion: 16
