name: Lint
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - '**'

jobs:
  lint:
    name: Check code base Format
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        path:
          - check: '.'
          - check: 'src'
    steps:
    - uses: actions/checkout@v3
    - name: Run clang-format style check for all codebase
      uses: jidicula/clang-format-action@v4.11.0
      with:
        clang-format-version: '16'
        check-path: ${{ matrix.path['check'] }}
        exclude-regex: ${{ matrix.path['exclude'] }}
